# $FreeBSD$

PORTNAME=	libibumad
PORTVERSION=	1.3.10.2
CATEGORIES=	sysutils
MASTER_SITES=	https://www.openfabrics.org/downloads/management/

MAINTAINER=	"Anthony Cornehl" <accornehl@fastmail.fm>

HAS_CONFIGURE=

.include <bsd.port.mk>
